### ISSUE TITLE
AUR package?

### ISSUE THREAD

**Issue by alter2000** [seebye/fmui#1]
I made a quick PKGBUILD and can be a maintainer, but I'll need some help:

* it makes no sense to keep them in the $PATH, so maybe somewhere in /usr/local/[lib|share] and then source them from there?
* should we force the user to install a visualizer, or leave both optional? I chose the latter just because I hate them.

The PKGBUILD is [here](https://gist.github.com/alter2000/fdf1ecc9072250e8b3510b9c92e54925).

**Comment by seebye** [comment]
According to the [arch wiki](https://wiki.archlinux.org/index.php/Arch_packaging_standards#Package_etiquette) packages shouldn't be installed to /usr/**local**.
> Packages should never be installed to /usr/local

> Package files should follow these general directory guidelines:
> [...]
> /usr/lib/{pkg} | Modules, plugins, etc.

So I guess the scripts should be placed in /usr/lib/fmui and /usr/bin/fmui should be a soft link to ../lib/fmui/fmui.

> should we force the user to install a visualizer, or leave both optional? I chose the latter just because I hate them.

It's okay not to include it.
cava requires a patch anyways otherwise it will produce a segmentation fault as it's not able to handle piped input.

**Comment by alter2000** [comment]
Done and tested by another person. Will have to fix mpd/pulseaudio permissions to test by myself.

**Comment by seebye** [comment]
Hey @alter2000,
there's going to be an update soon which allows to display cover images by using https://github.com/seebye/ueberzug.
So there will be a few new scripts and as far as I see you hardcoded the installation of each script.
E.g. `install -D -m755 ./actions.sh "${pkgdir}/usr/lib/$_pkgname"`
So it would be nice if you could replace
```bash
    install -D -m755 ./actions.sh "${pkgdir}/usr/lib/$_pkgname"
    install -D -m755 ./info.sh "${pkgdir}/usr/lib/$_pkgname"
    install -D -m755 ./keys.sh "${pkgdir}/usr/lib/$_pkgname"
```
with something like this:
```bash
for script in ./*.sh; do
    install -D -m755 "${script}" "${pkgdir}/usr/lib/$_pkgname"
done
```

**Comment by alter2000** [comment]
Done, thanks for the heads up!
