### ISSUE TITLE
Question: Why did you choose default keybinding which doesn't use a modifier

### ISSUE THREAD

**Issue by doronbehar** [seebye/fmui#2]
I was wondering, since search is done via pressing normal ASCII letters keys, why did you choose to use them for the [meta actions like "Go Down", "Go Up"](https://github.com/seebye/fmui#default-keybindings) etc.? How am I supposed to search for songs when a part of my keyboard is used for performing these actions?

**Comment by seebye** [comment]
I chose them as I want to use vim like keybindings.  
The keybindings are case senstivie so simply switch to uppercase to search for songs.  
If you prefer to search by default you can reconfigure the keybindings by creating a bash script "keybindings" in ~/.config/fmui/.

**Comment by doronbehar** [comment]
Thanks.
