### ISSUE TITLE
[Request] Toggle-able options box

### ISSUE THREAD

**Issue by teotwawki16** [seebye/fmui#6]
It would be nice if there's something like a configuration or a keybinding to show or hide the options box (I don't really know the name, but it's the one showing things like volume, repeat, etc.) to have that more minimalist player look. Thanks!

**Comment by seebye** [comment]
Adding `preview_box_size=0` to ~/.config/fmui/config will hide the preview pane.  

> keybinding to show or hide

As far as I know fzf does not support to change the size of the preview pane without restarting it.  
(toggle-pane can't be used as the preview pane is used to update the cover images)
